language: python
python:
 - "2.7"
 - "3.4"
 - "3.5"
env:
  global:
    - DRF="djangorestframework==3.3.2"
  matrix:
    - DJANGO="django==1.8"
    - DJANGO="django==1.9.1"
install:
 - pip install $DJANGO $DRF
script:
 - python setup.py test
